#!/usr/bin/env node
/**
 * Rebuild EXC from zero using the PRPM cache as a candidate pool.
 * Each round greedily selects 50 entries with the largest combined change in
 * forward/reverse exact-match accuracy; PRPM frequency breaks ties. Stops at
 * the first 50-entry boundary meeting the requested average accuracy.
 *
 * Dry run: node tools/optimize_exceptions.js
 * Apply:   node tools/optimize_exceptions.js --write
 */
const fs = require('fs');
const path = require('path');
const { spawnSync } = require('child_process');
const appEngine = require('./app_engine.js');

const ROOT = path.join(__dirname, '..');
const CACHE_PATH = path.join(ROOT, 'tools', 'prpm_cache.json');
const FREQUENCY_PATH = path.join(ROOT, 'tools', '10000.txt');
const GOLDEN_PATH = path.join(ROOT, 'tests', 'pedoman_cases.json');
const STEP = 50;
const TARGET = 0.99;
const BASE_EXC_COUNT = 0;
const FORMAT_CONTROLS = /[\u0080-\u009F\u200B-\u200F\u202A-\u202E\u2060-\u206F\uFEFF]/g;

function normalize(value) {
  return String(value)
    .normalize('NFC')
    .replace(FORMAT_CONTROLS, '')
    .replace(/\s+/g, ' ')
    .trim();
}

function parseArgs() {
  const args = process.argv.slice(2);
  const unknown = args.filter(arg => arg !== '--write');
  if (unknown.length) {
    throw new Error(`Unknown option(s): ${unknown.join(', ')}`);
  }
  return { write: args.includes('--write') };
}

function locateIncrement(source) {
  const declaration = 'const EXCEPTION_DICT_PRPM_INCREMENT = {';
  const assignment = 'Object.assign(EXCEPTION_DICT, EXCEPTION_DICT_PRPM_INCREMENT);';
  const declarationStart = source.indexOf(declaration);
  if (declarationStart < 0) throw new Error('Could not find EXCEPTION_DICT_PRPM_INCREMENT.');
  const commentStart = source.lastIndexOf('// PRPM-verified', declarationStart);
  const objectStart = source.indexOf('{', declarationStart);
  const objectEnd = source.indexOf('\n};', objectStart);
  if (objectEnd < 0) throw new Error('Could not find the end of EXC increment object.');
  const assignmentStart = source.indexOf(assignment, objectEnd);
  if (assignmentStart < 0) throw new Error('Could not find Object.assign for the EXC increment.');
  return { start: commentStart >= 0 ? commentStart : declarationStart,
    end: assignmentStart + assignment.length };
}

function formatObject(entries) {
  const lines = Object.entries(entries).map(([latin, jawi]) =>
    `  ${JSON.stringify(latin)}: ${JSON.stringify(jawi)}`
  );
  return lines.length ? ` {\n${lines.join(',\n')}\n}` : ' {}';
}

function renderIncrement(source, entries, baseCount) {
  const { start, end } = locateIncrement(source);
  const total = baseCount + Object.keys(entries).length;
  const batchComment = `// PRPM-verified EXC batch (+${Object.keys(entries).length}; ${baseCount} -> ${total}), generated by tools/optimize_exceptions.js.\n`;
  const block = `${batchComment}const EXCEPTION_DICT_PRPM_INCREMENT =${formatObject(entries)};\nObject.assign(EXCEPTION_DICT, EXCEPTION_DICT_PRPM_INCREMENT);`;
  return source.slice(0, start) + block + source.slice(end);
}

function loadEngine(source, increment) {
  const candidateSource = renderIncrement(source, increment, BASE_EXC_COUNT);
  return appEngine.loadEngine({ source: candidateSource });
}

function getReferenceRows(cache, engine) {
  return Object.entries(cache)
    .filter(([, jawi]) => typeof jawi === 'string' && jawi.trim())
    .map(([latin, rawJawi]) => {
      const jawi = normalize(rawJawi);
      return {
        latin,
        jawi,
        forward: normalize(engine.latinToJawi(latin)),
        reverse: normalize(engine.jawiToLatin(rawJawi))
      };
    });
}

function score(rows) {
  let forward = 0;
  let reverse = 0;
  for (const row of rows) {
    if (row.forward === row.jawi) forward++;
    if (row.reverse === normalize(row.latin.toLowerCase())) reverse++;
  }
  return {
    words: rows.length,
    forward,
    reverse,
    forwardAccuracy: forward / rows.length,
    reverseAccuracy: reverse / rows.length,
    average: (forward + reverse) / (2 * rows.length)
  };
}

function canonicalPedoman(value) {
  // U+06AC is the older ga glyph used by some transcriptions of the supplied
  // Pedoman; the app emits PRPM's current U+0762 form.
  return normalize(value).replace(/ڬ/g, 'ݢ');
}

function readPedomanCases() {
  return JSON.parse(fs.readFileSync(GOLDEN_PATH, 'utf8'));
}

function assertRuleOnlyPedoman(engine) {
  const cases = readPedomanCases().filter(testCase => testCase.phase !== 'exceptions');
  const errors = cases.filter(({ rumi, pedoman }) =>
    canonicalPedoman(engine.latinToJawi(rumi)) !== canonicalPedoman(pedoman)
  );
  if (errors.length) {
    const details = errors.slice(0, 5).map(({ rule, rumi, pedoman }) =>
      `${rule || '?'} ${rumi}: expected ${pedoman}, got ${engine.latinToJawi(rumi)}`
    ).join('\n  ');
    throw new Error(`Refusing to optimize exceptions: ${errors.length} rule-only Pedoman case(s) fail.\n  ${details}`);
  }
  return cases.length;
}

function getPedomanPolicy(cache, engine) {
  const cases = readPedomanCases();
  const protectedForms = new Map();
  const requiredWords = [];
  for (const { rumi, pedoman } of cases) {
    const expected = canonicalPedoman(pedoman);
    protectedForms.set(rumi.toLowerCase(), expected);
    const reference = cache[rumi];
    if (typeof reference === 'string' && canonicalPedoman(reference) === expected &&
        canonicalPedoman(engine.latinToJawi(rumi)) !== expected) {
      requiredWords.push(rumi);
    }
  }
  return { protectedForms, requiredWords: [...new Set(requiredWords)] };
}

function readFrequencies() {
  const result = new Map();
  for (const line of fs.readFileSync(FREQUENCY_PATH, 'utf8').split(/\r?\n/)) {
    const [word, count] = line.trim().split(/\s+/);
    if (word && count) result.set(word, Number(count) || 0);
  }
  return result;
}

function chooseBatch(rows, engine, frequencies, size, requiredWords = [], protectedForms = new Map()) {
  const reverseMap = new Map(Object.entries(engine.REVERSE_DICT));
  const byJawi = new Map();
  for (const row of rows) {
    if (!byJawi.has(row.jawi)) byJawi.set(row.jawi, []);
    byJawi.get(row.jawi).push(row);
  }

  const available = rows.filter(row => {
    if (engine.EXCEPTION_DICT[row.latin]) return false;
    const protectedForm = protectedForms.get(row.latin.toLowerCase());
    return !protectedForm || canonicalPedoman(row.jawi) === protectedForm;
  });
  const batch = [];
  function select(candidate) {
    const index = available.indexOf(candidate);
    if (index < 0) return false;
    batch.push(candidate);
    available.splice(index, 1);
    candidate.forward = candidate.jawi;
    if (!reverseMap.has(candidate.jawi)) {
      reverseMap.set(candidate.jawi, candidate.latin);
      for (const row of byJawi.get(candidate.jawi) || []) row.reverse = candidate.latin;
    }
    return true;
  }

  for (const word of requiredWords) {
    if (engine.EXCEPTION_DICT[word]) continue;
    const candidate = available.find(row => row.latin === word);
    if (!candidate) throw new Error(`Required Pedoman word is missing from PRPM candidates: ${word}`);
    select(candidate);
  }

  while (batch.length < size && available.length) {
    let best = null;
    let bestGain = -Infinity;
    let bestFrequency = -Infinity;

    for (const candidate of available) {
      let gain = candidate.forward === candidate.jawi ? 0 : 1;
      if (!reverseMap.has(candidate.jawi)) {
        for (const row of byJawi.get(candidate.jawi) || []) {
          const wasCorrect = row.reverse === normalize(row.latin.toLowerCase());
          const becomesCorrect = candidate.latin === row.latin;
          gain += Number(becomesCorrect) - Number(wasCorrect);
        }
      }
      const frequency = frequencies.get(candidate.latin) || 0;
      if (gain > bestGain || (gain === bestGain && frequency > bestFrequency)) {
        best = candidate;
        bestGain = gain;
        bestFrequency = frequency;
      }
    }

    if (!best) break;
    select(best);
  }
  return Object.fromEntries(batch.map(({ latin, jawi }) => [latin, jawi]));
}

function printScore(label, result, count) {
  console.log(`${label} — ${BASE_EXC_COUNT + count} EXC entries`);
  console.log(`  latin2jawi: ${result.forward}/${result.words} (${(result.forwardAccuracy * 100).toFixed(2)}%)`);
  console.log(`  jawi2latin: ${result.reverse}/${result.words} (${(result.reverseAccuracy * 100).toFixed(2)}%)`);
  console.log(`  average: ${(result.average * 100).toFixed(2)}%`);
}

function main() {
  const { write } = parseArgs();
  const originalSource = appEngine.readEngineSource();
  const cache = JSON.parse(fs.readFileSync(CACHE_PATH, 'utf8'));
  const frequencies = readFrequencies();
  let increment = {};
  let engine = loadEngine(originalSource, increment);
  const baseCount = Object.keys(engine.EXCEPTION_DICT).length;
  if (baseCount !== BASE_EXC_COUNT) {
    throw new Error(`Expected to restart from an empty EXC dictionary; found ${baseCount} entries.`);
  }

  const ruleCaseCount = assertRuleOnlyPedoman(engine);
  let rows = getReferenceRows(cache, engine);
  let result = score(rows);
  const { protectedForms, requiredWords } = getPedomanPolicy(cache, engine);
  console.log(`Rule-only Pedoman preflight: ${ruleCaseCount}/${ruleCaseCount} passed (EXC ignored).`);
  printScore('Rule-only baseline', result, 0);
  console.log(`Protecting ${protectedForms.size} Pedoman cases before PRPM exception optimization.`);
  if (requiredWords.length) {
    console.log(`Requiring ${requiredWords.length} PRPM-backed Pedoman spelling(s) in the selected EXC set.`);
  }
  if (result.average >= TARGET) {
    console.log('The base dictionary already meets the target; no increment is needed.');
    if (write) {
      appEngine.writeEngineSource(renderIncrement(originalSource, {}, baseCount));
    }
    return;
  }

  let batchNumber = 0;
  while (result.average < TARGET) {
    batchNumber++;
    const batch = chooseBatch(rows, engine, frequencies, STEP, requiredWords, protectedForms);
    if (Object.keys(batch).length !== STEP) {
      throw new Error(`Could not select a full ${STEP}-entry batch from the PRPM cache.`);
    }
    increment = { ...increment, ...batch };
    engine = loadEngine(originalSource, increment);
    rows = getReferenceRows(cache, engine);
    result = score(rows);
    printScore(`After +${STEP} (round ${batchNumber})`, result, Object.keys(increment).length);
  }

  console.log(`Selected ${Object.keys(increment).length} entries from scratch (${batchNumber} x ${STEP}).`);
  if (write) {
    appEngine.writeEngineSource(renderIncrement(originalSource, increment, baseCount));
    const checks = spawnSync(process.execPath, ['tests/evaluate_prpm.js'], {
      cwd: ROOT,
      encoding: 'utf8'
    });
    process.stdout.write(checks.stdout || '');
    process.stderr.write(checks.stderr || '');
    if (checks.status !== 0) throw new Error('Post-write PRPM evaluation failed.');
    console.log('Rebuilt the EXC increment directly inside JawiConverter.html.');
  } else {
    console.log('Dry run only. Use --write to replace the inline increment in JawiConverter.html.');
  }
}

try {
  main();
} catch (error) {
  console.error(error.stack || error.message || error);
  process.exitCode = 1;
}
